# Generated by Django 3.2.16 on 2023-03-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'My Subscriber', 'verbose_name_plural': 'A lot of Subscribers'},
        ),
    ]
