# Generated by Django 3.2.16 on 2023-03-17 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_productinbasket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInBasket',
        ),
    ]
