# Generated by Django 3.2.16 on 2023-03-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_discription',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
