# Generated by Django 3.2.16 on 2023-05-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.CharField(max_length=1000)),
                ('data', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
