# Generated by Django 3.2.16 on 2023-05-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230514_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='data',
            new_name='date',
        ),
    ]
